### PR TITLE
solved issue 17, added support for cleverbot API keys

### PR DESCRIPTION
**Pull request by frankplus**
added support for new cleverbot-node module version 0.3.11 and Cleverbot new API key interface

### CODE REVIEW

**Comment by clux** [comment]
Hey, thanks. I'd forgotten about this completely.

So we only need an extra `configure` call with the api key in the new version of cleverbot-node? We should probably have that configurable in the config as well.

**Comment by frankplus** [comment]
That's right, we only need an extra configure call and  change the cleverbot-node module version as stated in the documentation: 
Changes from 0.2.x
- API Key is now required
- Cleverbot.prepare call is no longer needed. It is now a noop for backwards compatibility
- The output of the bot is now in the output attribute of the response object. It is copied to message for backwards compatibility

Yes, it would be a good idea to integrate that in the .clvr.json file as well but I don't know how to do that.

**Comment by clux** [comment]
Ok, that's fine. Thanks for the info. I'll merge and rework your changeset to incorporate a config change later today.

**Comment by clux** [comment]
Released cleverbot-irc@1.2.0 that can take the key as an environment variable. Should at least work.

Unfortunately, I screwed up the cfg parsing so will have to fix that later in 1.2.1.

**Comment by clux** [comment]
Ok, fixed in 1.3.0

**Pull request closed without merging**
